name: Create Release from tag
on:
  push:
    tags:
      - '*'
jobs:
  create-release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          java-version: '11'
          distribution: 'temurin'
          cache: gradle
      - name: Grant execute permission for gradlew
        run: chmod +x gradlew
      - name: Build with Gradle
        run: ./gradlew build
      - name: Upload Release
        uses: ncipollo/release-action@v1
        with:
            artifacts: lib1/build/outputs/aar/lib1-debug.aar
            token: ${{ secrets.GITHUB_TOKEN }}
